driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_path: test/shared

platforms:
  - name: centos-5.11
  - name: centos-6.8
  - name: centos-7.2
  - name: debian-7.11
    run_list: apt::default
  - name: debian-8.5
    run_list: apt::default
  - name: fedora-24
    run_list: yum::dnf_yum_compat
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-16.04
    run_list: apt::default

suites:
  - name: tinydns
    run_list:
      - recipe[test]
    attributes:
      domain: test.local
      djbdns:
        service_type: runit
  - name: source
    run_list:
      - recipe[test]
    attributes:
      domain: test.local
      djbdns:
        install_method: source

  - name: dbndns
    run_list:
      - recipe[test]
    includes:
      - ubuntu-14.04
    attributes:
      domain: test.local
      djbdns:
        package_name: dbndns
