driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: centos-6.8
  - name: centos-7.3
  - name: debian-7.11
  - name: debian-8.7
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: tinydns
    run_list:
      - recipe[test]
    attributes:
      domain: test.local
      djbdns:
        service_type: runit
  - name: source
    run_list:
      - recipe[test]
    attributes:
      domain: test.local
      djbdns:
        install_method: source

  - name: dbndns
    run_list:
      - recipe[test]
    includes:
      - ubuntu-14.04
    attributes:
      domain: test.local
      djbdns:
        package_name: dbndns
