---
driver:
  name: vagrant
  customize:
    memory: 512

provisioner:
  name: chef_zero
  data_path: test/shared

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: ubuntu-10.04
  - name: debian-7.6
  - name: centos-6.5
  - name: centos-5.10

suites:
  - name: tinydns
    run_list:
      - recipe[test]
    attributes:
      djbdns:
        service_type: runit
  - name: source
    run_list:
      - recipe[test]
    attributes:
      djbdns:
        service_type: runit
        install_method: source

  - name: dbndns
    run_list:
      - recipe[test]
    excludes:
      - ubuntu-12.04
      - ubuntu-10.04
      - debian-7.6
      - centos-6.5
      - centos-5.10
    attributes:
      djbdns:
        package_name: dbndns
