AllCops:
  Include:
    - Berksfile
    - Gemfile
    - Rakefile
    - Thorfile
    - Guardfile
  Exclude:
    - vendor/**

ClassLength:
  Enabled: false
Documentation:
  Enabled: false
Encoding:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
SignalException:
  Enabled: false
WordArray:
  Enabled: false

Style/SingleSpaceBeforeFirstArg:
  Exclude:
    - '**/Rakefile'
    - '**/metadata.rb'

Style/PercentLiteralDelimiters:
  Exclude:
    - '**/metadata.rb'
